apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "secret-store"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: dbusername
  secretObjects:
    - secretName: "secret-store"
      type: Opaque
      data:
        - objectName: dbusername
          key: db_username_01
